[package]
name = "bpg"
version = "0.1.0"
edition = "2021"

[dependencies]
bitcoin = { version = "0.32.0", features = ["serde"] }
clap = { version = "4.5.4", features = ["derive"] }
serde = "1.0.200"
serde_json = "1.0.116"
